CREATE TABLE STUDENTS(
    ROOL_NO INT auto_increment,
    NAME VARCHAR(20) NOT NULL,
    BRANCH VARCHAR(20),
    PRIMARY KEY(ROOL_NO)
);

-- DESCRIBE STUDENTS;

-- DROP TABLE STUDENTS;

ALTER TABLE STUDENTS ADD CGPA DECIMAL(3, 2) UNIQUE;

-- ALTER TABLE STUDENTS DROP COLUMN CGPA;

INSERT INTO STUDENTS(NAME,BRANCH,CGPA) VALUES('VASANTH','EEE',7.16);
INSERT INTO STUDENTS(NAME,BRANCH,CGPA) VALUES('RAMA','IT',6.96);
INSERT INTO STUDENTS(NAME,BRANCH,CGPA) VALUES('OMNATH','IT',7.10);
INSERT INTO STUDENTS(NAME,BRANCH,CGPA) VALUES('UMA','IT',6.8);
INSERT INTO STUDENTS(NAME,BRANCH,CGPA)VALUES('MALLI','EEE',6.78);
SELECT * FROM STUDENTS;

-- INSERT INTO STUDENTS VALUES(264,'VASANTH','EEE',7.16);

-- SELECT * FROM STUDENTS;
UPDATE STUDENTS
SET BRANCH ='IT'
WHERE BRANCH='EEE';
SELECT * FROM STUDENTS; 

DELETE FROM STUDENTS
WHERE ROOL_NO=4;
-- SELECT * FROM STUDENTS;



-- DELETE FROM STUDENTS;
SELECT * FROM STUDENTS;


